import { ThemeType, ThemeConfig } from '../types';


export const THEME_CONFIGS: Record<ThemeType, ThemeConfig> = {
  sunny: {
    id: 'sunny',
    name: 'Sunny Day',
    icon: 'fa-sun',
    background: 'bg-gradient-to-b from-sky-100 via-white to-green-50',
    cardBg: 'bg-white/60 border-white/60',
    text: 'text-slate-800',
    subText: 'text-slate-600',
    accent: 'text-brand',
    button: 'bg-gradient-to-r from-brand to-brand-dark',
    headerBg: 'bg-white/70 border-white/50',
    iconBg: 'bg-white/80 border-white text-slate-600 hover:text-brand'
  },
  night: {
    id: 'night',
    name: 'Starry Night',
    icon: 'fa-moon',
    background: 'bg-gradient-to-b from-slate-900 via-indigo-950 to-slate-900',
    cardBg: 'bg-slate-800/60 border-indigo-500/30',
    text: 'text-indigo-50',
    subText: 'text-indigo-300',
    accent: 'text-yellow-300',
    button: 'bg-gradient-to-r from-indigo-600 to-purple-700',
    headerBg: 'bg-slate-900/70 border-slate-700/50',
    iconBg: 'bg-slate-800/80 border-slate-700 text-indigo-300 hover:text-yellow-300'
  },
  candy: {
    id: 'candy',
    name: 'Candy Land',
    icon: 'fa-candy-cane',
    background: 'bg-gradient-to-b from-pink-100 via-purple-50 to-pink-50',
    cardBg: 'bg-white/70 border-pink-200/60',
    text: 'text-purple-900',
    subText: 'text-purple-600',
    accent: 'text-pink-500',
    button: 'bg-gradient-to-r from-pink-400 to-purple-400',
    headerBg: 'bg-white/70 border-pink-100/50',
    iconBg: 'bg-white/80 border-white text-pink-400 hover:text-purple-500'
  },
  forest: {
    id: 'forest',
    name: 'Magic Forest',
    icon: 'fa-tree',
    background: 'bg-gradient-to-b from-emerald-100 via-teal-50 to-emerald-50',
    cardBg: 'bg-white/60 border-emerald-200/60',
    text: 'text-emerald-900',
    subText: 'text-emerald-700',
    accent: 'text-teal-600',
    button: 'bg-gradient-to-r from-emerald-500 to-teal-600',
    headerBg: 'bg-white/70 border-emerald-100/50',
    iconBg: 'bg-white/80 border-white text-emerald-600 hover:text-teal-700'
  },
  park: {
    id: 'park',
    name: 'Puppy Park',
    icon: 'fa-baseball-ball',
    background: 'bg-gradient-to-b from-green-100 via-lime-50 to-sky-100',
    cardBg: 'bg-white/60 border-lime-300/60',
    text: 'text-emerald-800',
    subText: 'text-emerald-600',
    accent: 'text-lime-600',
    button: 'bg-gradient-to-r from-lime-500 to-green-600',
    headerBg: 'bg-white/70 border-lime-200/50',
    iconBg: 'bg-white/80 border-white text-lime-600 hover:text-green-700'
  },
  bath: {
    id: 'bath',
    name: 'Bubble Bath',
    icon: 'fa-bath',
    background: 'bg-gradient-to-b from-cyan-100 via-blue-50 to-white',
    cardBg: 'bg-white/70 border-cyan-200/60',
    text: 'text-cyan-900',
    subText: 'text-cyan-700',
    accent: 'text-blue-500',
    button: 'bg-gradient-to-r from-cyan-400 to-blue-500',
    headerBg: 'bg-white/70 border-cyan-100/50',
    iconBg: 'bg-white/80 border-white text-cyan-500 hover:text-blue-600'
  },
  toys: {
    id: 'toys',
    name: 'Toy Paradise',
    icon: 'fa-puzzle-piece',
    background: 'bg-gradient-to-b from-yellow-100 via-red-50 to-blue-50',
    cardBg: 'bg-white/70 border-orange-200/60',
    text: 'text-slate-800',
    subText: 'text-slate-600',
    accent: 'text-orange-500',
    button: 'bg-gradient-to-r from-orange-400 to-red-500',
    headerBg: 'bg-white/70 border-yellow-100/50',
    iconBg: 'bg-white/80 border-white text-orange-500 hover:text-red-500'
  },
  streetDog: {
    id: 'streetDog',
    name: 'Street Dog',
    icon: 'fa-bolt',
    background: 'bg-yellow-200',
    cardBg: 'bg-white border-4 border-black shadow-[6px_6px_0_black]',
    text: 'text-black',
    subText: 'text-gray-700',
    accent: 'text-red-600',
    button: 'bg-red-600 text-white border-4 border-black',
    headerBg: 'bg-white border-b-4 border-black',
    iconBg: 'bg-black text-yellow-300 hover:scale-110'
  },
  puppyPlush: {
    id: 'puppyPlush',
    name: 'Puppy Plush',
    icon: 'fa-heart',
    background: 'bg-[#FFF6E9]',
    cardBg: 'bg-[#FFE4C4] border-none shadow-md rounded-2xl',
    text: 'text-[#5A3E2B]',
    subText: 'text-[#8B6B4F]',
    accent: 'text-[#FF9F68]',
    button: 'bg-[#FFB085] text-[#5A3E2B]',
    headerBg: 'bg-[#FFDAB9]',
    iconBg: 'bg-[#FFB085] text-white'
  },
  dogParkDark: {
    id: 'dogParkDark',
    name: 'Dog Park Dark',
    icon: 'fa-bone',
    background: 'bg-gradient-to-br from-slate-900 via-emerald-900 to-black',
    cardBg: 'bg-slate-800 border border-emerald-500/30 shadow-2xl',
    text: 'text-emerald-300',
    subText: 'text-slate-400',
    accent: 'text-emerald-400',
    button: 'bg-emerald-600 hover:bg-emerald-500 text-black',
    headerBg: 'bg-black border-b border-emerald-600',
    iconBg: 'bg-slate-700 text-emerald-400 hover:shadow-emerald-500/50'
  },
  puppyCandy: {
    id: 'puppyCandy',
    name: 'Puppy Candy',
    icon: 'fa-dog',
    background: 'bg-gradient-to-br from-pink-300 via-yellow-200 to-sky-300',
    cardBg: 'bg-white shadow-xl border-4 border-pink-300 rounded-3xl',
    text: 'text-pink-900',
    subText: 'text-pink-700',
    accent: 'text-yellow-500',
    button: 'bg-yellow-400 text-pink-900 hover:scale-110 transition-all',
    headerBg: 'bg-pink-200 border-b-4 border-yellow-400',
    iconBg: 'bg-yellow-300 text-pink-900 shadow-lg hover:rotate-12'
  },
  neonPup: {
    id: 'neonPup',
    name: 'Neon Pup Arcade',
    icon: 'fa-bolt',
    background: 'bg-black bg-[radial-gradient(circle_at_top,_#22d3ee,_transparent_60%)]',
    cardBg: 'bg-black border-2 border-cyan-400 shadow-[0_0_30px_#22d3ee]',
    text: 'text-cyan-300',
    subText: 'text-fuchsia-400',
    accent: 'text-lime-400',
    button: 'bg-cyan-500 text-black hover:shadow-[0_0_25px_#22d3ee]',
    headerBg: 'bg-black border-b-2 border-cyan-400',
    iconBg: 'bg-black text-cyan-400 hover:text-fuchsia-500'
  },
  handDrawnPup: {
    id: 'handDrawnPup',
    name: 'Hand-Drawn Puppy',
    icon: 'fa-pencil',
    background: 'bg-[#FFFDF7] bg-[linear-gradient(90deg,#00000008_1px,transparent_1px)] bg-[size:24px_24px]',
    cardBg: 'bg-[#FFFAF0] border-2 border-dashed border-amber-600 rotate-[-1deg]',
    text: 'text-amber-900',
    subText: 'text-amber-700',
    accent: 'text-rose-600',
    button: 'bg-amber-400 text-black rotate-[1deg]',
    headerBg: 'bg-[#FFF1D6] border-b-2 border-dashed border-amber-700',
    iconBg: 'bg-[#FFE8C2] text-amber-800 hover:rotate-6'
  },
  cosmicPuppy: {
    id: 'cosmicPuppy',
    name: 'Cosmic Puppy',
    icon: 'fa-moon',
    background: 'bg-gradient-to-br from-indigo-900 via-purple-900 to-black',
    cardBg: 'bg-indigo-800/60 backdrop-blur-xl border border-purple-400/30',
    text: 'text-purple-200',
    subText: 'text-indigo-300',
    accent: 'text-pink-400',
    button: 'bg-gradient-to-r from-pink-500 to-purple-500',
    headerBg: 'bg-indigo-950 border-b border-purple-500/40',
    iconBg: 'bg-indigo-900 text-pink-400 hover:shadow-pink-500/50'
  },
  safariPup: {
    id: 'safariPup',
    name: 'Safari Pup',
    icon: 'fa-compass',
    background: 'bg-gradient-to-b from-lime-200 via-amber-100 to-orange-100',
    cardBg: 'bg-[#F5E6C8] border border-[#A67C52] shadow-md',
    text: 'text-[#4A3A1A]',
    subText: 'text-[#7A5C2E]',
    accent: 'text-[#2F855A]',
    button: 'bg-[#A67C52] text-white',
    headerBg: 'bg-[#EAD7B7] border-b border-[#A67C52]',
    iconBg: 'bg-[#C8AD7F] text-[#4A3A1A]'
  },
  puppyHologram: {
    id: 'puppyHologram',
    name: 'Puppy Hologram',
    icon: 'fa-circle',
    background: 'bg-gradient-to-br from-slate-900 to-black',
    cardBg: 'bg-white/10 backdrop-blur-2xl border border-white/20',
    text: 'text-white',
    subText: 'text-slate-300',
    accent: 'text-cyan-300',
    button: 'bg-white/20 hover:bg-white/30',
    headerBg: 'bg-black/40 border-b border-white/20',
    iconBg: 'bg-white/10 text-cyan-300 hover:ring-2 ring-cyan-400'
  },
  cartoonChaos: {
    id: 'cartoonChaos',
    name: 'Cartoon Chaos Pup',
    icon: 'fa-face-laugh',
    background: 'bg-gradient-to-r from-red-300 via-yellow-300 to-blue-300',
    cardBg: 'bg-white border-4 border-purple-600 rotate-2 shadow-xl',
    text: 'text-purple-800',
    subText: 'text-blue-700',
    accent: 'text-red-600',
    button: 'bg-purple-600 text-white hover:scale-110',
    headerBg: 'bg-yellow-300 border-b-4 border-purple-600',
    iconBg: 'bg-red-500 text-white hover:rotate-12'
  },
};

