import React from 'react';

interface InfoModalProps {
  onClose: () => void;
}

export const InfoModal: React.FC<InfoModalProps> = ({ onClose }) => (
  <div className="absolute inset-0 z-[100] bg-black/60 backdrop-blur-sm flex items-start justify-center pt-4 px-4 animate-fade-in overflow-hidden">
    <div className="bg-white rounded-[2rem] w-full max-w-md shadow-2xl relative max-h-[calc(90vh-2rem)] flex flex-col border-4 border-white overflow-hidden">
      {/* Header - Fixed */}
      <div className="flex-shrink-0 p-6 pb-4 border-b border-slate-100">
        <div className="flex justify-between items-center">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-brand-light rounded-full flex items-center justify-center shadow-sm">
              <i className="fas fa-book-open text-brand text-lg"></i>
            </div>
            <h3 className="text-2xl font-black text-slate-800">Explorer's Guide</h3>
          </div>
          <button 
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-slate-100 text-slate-400 hover:bg-slate-200 hover:text-slate-600 flex items-center justify-center transition-colors"
          >
            <i className="fas fa-times"></i>
          </button>
        </div>
      </div>

      {/* Scrollable Content */}
      <div className="flex-1 overflow-y-auto overflow-x-hidden p-6 pt-4 hide-scrollbar">
        <div className="space-y-6">
        {/* Intro */}
        <p className="text-slate-600 text-sm font-medium leading-relaxed">
           Welcome to <strong>FindMyPuppy</strong>! Explore magical worlds generated by AI and rescue the puppies hiding in plain sight.
        </p>

        {/* Game Modes Table */}
        <div className="border border-slate-200 rounded-xl overflow-hidden shadow-sm">
           <div className="bg-slate-100 p-3 flex justify-between items-center border-b border-slate-200">
              <h4 className="font-bold text-slate-700 text-sm uppercase tracking-wider">Game Modes Breakdown</h4>
           </div>
           <div className="divide-y divide-slate-100">
              {/* Easy */}
              <div className="grid grid-cols-4 gap-2 p-3 bg-white items-center">
                 <div className="col-span-1 font-bold text-emerald-600 text-xs uppercase">Easy</div>
                 <div className="col-span-3 text-xs text-slate-600 space-y-1">
                    <div className="flex items-center gap-2"><i className="fas fa-clock w-4 text-center text-slate-400"></i> <span>No Timer (Relaxed)</span></div>
                    <div className="flex items-center gap-2"><i className="fas fa-paw w-4 text-center text-slate-400"></i> <span>15-25 Pups</span></div>
                    <div className="flex items-center gap-2"><i className="fas fa-star w-4 text-center text-yellow-500"></i> <span>+10 Points / Level</span></div>
                 </div>
              </div>
              {/* Medium */}
              <div className="grid grid-cols-4 gap-2 p-3 bg-slate-50 items-center">
                 <div className="col-span-1 font-bold text-blue-600 text-xs uppercase">Medium</div>
                 <div className="col-span-3 text-xs text-slate-600 space-y-1">
                    <div className="flex items-center gap-2"><i className="fas fa-clock w-4 text-center text-slate-400"></i> <span>150 Seconds (2m 30s)</span></div>
                    <div className="flex items-center gap-2"><i className="fas fa-paw w-4 text-center text-slate-400"></i> <span>25-35 Pups</span></div>
                    <div className="flex items-center gap-2"><i className="fas fa-star w-4 text-center text-yellow-500"></i> <span>+20 Points / Level</span></div>
                 </div>
              </div>
              {/* Hard */}
              <div className="grid grid-cols-4 gap-2 p-3 bg-white items-center">
                 <div className="col-span-1 font-bold text-rose-600 text-xs uppercase">Hard</div>
                 <div className="col-span-3 text-xs text-slate-600 space-y-1">
                    <div className="flex items-center gap-2"><i className="fas fa-clock w-4 text-center text-slate-400"></i> <span>180 Seconds (3m)</span></div>
                    <div className="flex items-center gap-2"><i className="fas fa-paw w-4 text-center text-slate-400"></i> <span>40-50 Pups (Tiny!)</span></div>
                    <div className="flex items-center gap-2"><i className="fas fa-star w-4 text-center text-yellow-500"></i> <span>+50 Points / Level</span></div>
                 </div>
              </div>
           </div>
        </div>

        {/* Hint Economy */}
        <div className="bg-yellow-50 rounded-xl p-4 border border-yellow-100 relative overflow-hidden">
           <i className="fas fa-lightbulb absolute -top-4 -right-2 text-8xl text-yellow-400/10 rotate-12"></i>
           <h4 className="font-bold text-yellow-900 mb-2 flex items-center gap-2 relative z-10 text-sm uppercase tracking-wider">
             <i className="fas fa-coins text-yellow-500"></i> Hint System
           </h4>
           <div className="relative z-10 space-y-3">
              <div className="flex items-start gap-3">
                 <div className="bg-white p-1.5 rounded-lg shadow-sm text-brand"><i className="fas fa-gift"></i></div>
                 <div>
                    <span className="block text-xs font-bold text-yellow-800">Daily Free Hints</span>
                    <span className="text-[10px] text-yellow-800/80">You get <strong className="text-brand-dark">2 Free Hints</strong> every single level. They reset when you start a new game!</span>
                 </div>
              </div>
              <div className="flex items-start gap-3">
                 <div className="bg-white p-1.5 rounded-lg shadow-sm text-indigo-500"><i className="fas fa-exchange-alt"></i></div>
                 <div>
                    <span className="block text-xs font-bold text-yellow-800">Use Your Points</span>
                    <span className="text-[10px] text-yellow-800/80">Run out of free hints? Exchange your score! <br/><strong className="bg-white/50 px-1 rounded text-indigo-700">10 Points = 2 Premium Hints</strong></span>
                 </div>
              </div>
              <div className="flex items-start gap-3">
                 <div className="bg-white p-1.5 rounded-lg shadow-sm text-green-500"><i className="fas fa-shopping-cart"></i></div>
                 <div>
                    <span className="block text-xs font-bold text-yellow-800">Shop (Simulated)</span>
                    <span className="text-[10px] text-yellow-800/80">Support the dev by buying hint packs. <br/>(This is a demo payment flow using UPI deep links).</span>
                 </div>
              </div>
           </div>
        </div>

        {/* Controls & Progression */}
        <div className="grid grid-cols-2 gap-3">
           <div className="bg-slate-50 p-3 rounded-xl border border-slate-100">
              <h5 className="font-bold text-slate-700 text-xs mb-1"><i className="fas fa-hand-pointer mr-1"></i> Controls</h5>
              <ul className="text-[10px] text-slate-500 list-disc pl-3">
                 <li>Tap puppies to collect.</li>
                 <li>Pinch to Zoom in/out.</li>
                 <li>Drag to pan the map.</li>
              </ul>
           </div>
           <div className="bg-slate-50 p-3 rounded-xl border border-slate-100">
              <h5 className="font-bold text-slate-700 text-xs mb-1"><i className="fas fa-layer-group mr-1"></i> Progression</h5>
              <p className="text-[10px] text-slate-500">
                 Every <strong>5 levels</strong>, the puppies get smaller and more transparent! Can you reach level 100?
              </p>
           </div>
        </div>
        
        {/* Copyright Footer */}
        <div className="pt-2 text-center">
             <div className="w-12 h-1 bg-slate-100 rounded-full mx-auto mb-2"></div>
             <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider opacity-60">© 2025-2026 MVTechnology</p>
        </div>
        </div>
      </div>
    </div>
  </div>
);

